SET(RABBITIM_SOURCES ${CMAKE_SOURCE_DIR}/Plugin/PluginStatic.cpp)

SET(RABBITIM_LIBS ${RABBITIM_LIBS} Lbs)
SET(RABBITIM_LIBS ${RABBITIM_LIBS} ProtocolQXmpp)
SET(RABBITIM_LIBS ${RABBITIM_LIBS} QRCode)
SET(RABBITIM_LIBS ${RABBITIM_LIBS} ScreenShot)
SET(RABBITIM_LIBS ${RABBITIM_LIBS} Update)