
SET(RABBITIM_SOURCES
    main.cpp
    MainWindow.cpp 
    Tool.cpp 
    Client/ClientXmpp.cpp 
    Client/Client.cpp 
    UserInfo/UserInfo.cpp 
    UserInfo/UserInfoXmpp.cpp 
    UserInfo/COperateRoster.cpp 
    Global/Global.cpp 
    Widgets/FrmLogin/FrmLogin.cpp 
    Widgets/FrmUserList/FrmUserList.cpp 
    Widgets/FrmUserList/GroupItem.cpp 
    Widgets/FrmRegister/FrmRegister.cpp 
    Widgets/FrmAbout/FrmAbout.cpp 
    Widgets/FrmCustom/CustomTreeView.cpp 
    Widgets/FrmVideo/RecordAudio.cpp 
    Widgets/FrmLogin/FrmLoginSettings.cpp 
    Widgets/FrmUservCard/FrmUservCard.cpp 
    Widgets/FrmCustom/Label.cpp  
    Widgets/FrmMain/FrmMain.cpp  
    Manager/Manager.cpp 
    Manager/ManagerXmpp.cpp 
    Manager/ManageMessageDialog.cpp 
    Widgets/FrmMessage/FrmMessage.cpp 
    Widgets/FrmCustom/MenuMessageSend.cpp  
    Manager/ManageMessageDialogBigScreen.cpp 
    Widgets/FrmMessage/FrmContainer.cpp 
    Message/Message.cpp 
    Message/ChatActions/ChatAction.cpp 
    Message/ChatActions/MessageAction.cpp 
    UserInfo/User.cpp 
    Manager/ManageUser.cpp 
    Manager/ManageUserQXmpp.cpp 
    Message/SmileyPack.cpp 
    Message/EmoticonsWidget.cpp 
    Message/style.cpp 
    Widgets/FrmRecentMessage/FrmRecentMsgList.cpp 
    Widgets/FrmRecentMessage/ManageRecentMessage.cpp 
    Widgets/DlgOptions/DlgOptions.cpp 
    Widgets/DlgAddRoster/DlgAddRoster.cpp 
    FileTransfer/ManageFileTransfer.cpp 
    FileTransfer/FileTransfer.cpp 
    FileTransfer/FileTransferQXmpp.cpp   
    Message/ChatActions/FileTransferAction.cpp
)

SET(RABBITIM_UIS
    MainWindow.ui
    Widgets/FrmLogin/FrmLogin.ui
    Widgets/FrmUserList/FrmUserList.ui
    Widgets/FrmRegister/FrmRegister.ui
    Widgets/FrmAbout/FrmAbout.ui
    Widgets/FrmMain/FrmMain.ui
    Widgets/FrmLogin/FrmLoginSettings.ui
    Widgets/DlgOptions/DlgOptions.ui
    Widgets/FrmUservCard/FrmUservCard.ui
    Widgets/FrmMessage/FrmMessage.ui
    Widgets/FrmMessage/FrmContainer.ui
    Widgets/FrmRecentMessage/FrmRecentMsgList.ui
    Widgets/DlgAddRoster/DlgAddRoster.ui
    #Widgets/FrmGroupChat/FrmGroupChatList.ui
    #Widgets/FrmGroupChat/FrmGroupChatFind.ui
    #Widgets/FrmGroupChat/FrmGroupChat.ui
    #Widgets/FrmGroupChat/FrmCreateGroupChatRoom.ui
    #Widgets/FrmVideo/FrmVideo.ui 
)
