#TODO:发行版本时，需要修改下列值  
SET(MAJOR_VERSION_NUMBER 0)      #主版本
SET(MINOR_VERSION_NUMBER 1)       #次版本
SET(REVISION_VERSION_NUMBER 0)  #修订号

configure_file(
  ${CMAKE_CURRENT_SOURCE_DIR}/Update/Version.h.template.cmake
  ${CMAKE_CURRENT_SOURCE_DIR}/Version.h
)

configure_file(
  ${CMAKE_CURRENT_SOURCE_DIR}/Update/Update.xml.template.cmake
  ${CMAKE_CURRENT_SOURCE_DIR}/Update/Update_${RABBITIM_SYSTEM}.xml
)

# Compiler Runtime DLLs
IF(MSVC)
  # Visual Studio
  set(CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP true)
  include(InstallRequiredSystemLibraries)
  install(FILES ${CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS} DESTINATION .)
elseif(MINGW)
  # MinGW
  get_filename_component(MINGW_DLL_DIR ${CMAKE_CXX_COMPILER} PATH)
  install(FILES
    ${MINGW_DLL_DIR}/libgcc_s_dw2-1.dll
    ${MINGW_DLL_DIR}/libstdc++-6.dll
    ${MINGW_DLL_DIR}/libwinpthread-1.dll
    DESTINATION .
  )
endif()

SET(CPACK_PACKAGE_VERSION_MAJOR "${MAJOR_VERSION_NUMBER}")
SET(CPACK_PACKAGE_VERSION_MINOR "${MINOR_VERSION_NUMBER}")
SET(CPACK_PACKAGE_VERSION_PATCH "${REVISION_VERSION_NUMBER}")
SET(CPACK_PACKAGE_DESCRIPTION "Rabbit instant messaging")
SET(CPACK_PACKAGE_CONTACT "kl222@126.com")
SET(CPACK_PACKAGE_VENDOR "KangLin studio")


IF(WIN32 AND NOT UNIX)
    SET(CPACK_NSIS_INSTALLED_ICON_NAME "bin\\\\${PROJECT_NAME}.exe")
    SET(CPACK_NSIS_DISPLAY_NAME "${CPACK_PACKAGE_INSTALL_DIRECTORY}${PROJECT_NAME}")
    SET(CPACK_NSIS_MODIFY_PATH ON)
ELSE(WIN32 AND NOT UNIX)
    SET(CPACK_PACKAGE_ICON "${CMAKE_SOURCE_DIR}/AppIcon.ico")
ENDIF(WIN32 AND NOT UNIX)


#SET(CPACK_DEBIAN_PACKAGE_DEPENDS "libc6 (>= 2.17)")

include(CPack)
