MACRO(INSTALL_QT_LIBRARY _NAME)
  IF(WIN32)
    SET(_PREFIX "Qt5")
    SET(_EXT "dll")
  ELSE(WIN32)
    SET(_PREFIX "libQt5")
    SET(_EXT "so")
  ENDIF(WIN32)
  SET(_LIB "${QT_INSTALL_DIR}/bin/${_PREFIX}${_NAME}.${_EXT}")
  IF(EXISTS ${_LIB})
    INSTALL(FILES ${_LIB} DESTINATION ${CMAKE_INSTALL_PREFIX})
  ENDIF(EXISTS ${_LIB})
ENDMACRO(INSTALL_QT_LIBRARY)

MACRO(INSTALL_QT_PLUGINS _PLUGINS_PARA)
    FOREACH(_plugins ${ARGV})
        message("plugin:${_plugins}")
        SET(_plugins ${_plugins})
        FOREACH(_plugin ${${_plugins}})
            get_target_property(_plugin_file ${_plugin} LOCATION)
            if(_plugin_file)
                #STRING(REGEX MATCH "plugins(.*)" _des_plugin_file ${_plugin_file})
                STRING(REGEX REPLACE "^.*(plugins.*)/.*.dll$" "\\1" _des_plugin_file ${_plugin_file})
                #message("Plugin ${_plugin} is at location ${_plugin_file}\n_des_file:${_des_plugin_file}\n")
                INSTALL(FILES ${_plugin_file} DESTINATION "${CMAKE_INSTALL_PREFIX}/${_des_plugin_file}")
            endif()
        ENDFOREACH()
    ENDFOREACH()
ENDMACRO(INSTALL_QT_PLUGINS)

MACRO(INSTALL_QT_LIBRARYS _LIBS)
    foreach(_file  ${ARGV})
        get_target_property(_location ${_file} LOCATION)
        IF(EXISTS ${_location})
            INSTALL(FILES ${_location} DESTINATION ${CMAKE_INSTALL_PREFIX})
        ENDIF(EXISTS ${_location})
        #message("_file:${_file}\n")
    endforeach()
ENDMACRO(INSTALL_QT_LIBRARYS)
