MACRO(INSTALL_QT_LIBRARY _NAME)
  IF(WIN32)
    SET(_PREFIX "Qt5")
    SET(_EXT "dll")
  ELSE(WIN32)
    SET(_PREFIX "libQt5")
    SET(_EXT "so")
  ENDIF(WIN32)
  SET(_LIB "${QT_INSTALL_DIR}/bin/${_PREFIX}${_NAME}.${_EXT}")
  IF(EXISTS ${_LIB})
    INSTALL(FILES ${_LIB} DESTINATION ${CMAKE_INSTALL_PREFIX})
  ENDIF(EXISTS ${_LIB})
ENDMACRO(INSTALL_QT_LIBRARY)

MACRO(INSTALL_QT_LIBRARYS _LIBS)
    foreach(_file  ${ARGV})
        get_target_property(_location ${_file} LOCATION)
        IF(EXISTS ${_location})
            INSTALL(FILES ${_location} DESTINATION ${CMAKE_INSTALL_PREFIX})
        ENDIF(EXISTS ${_location})
    endforeach()
ENDMACRO(INSTALL_QT_LIBRARYS)
