name: Codespell

on:
  push:
  pull_request:
  
jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          path: ${{github.workspace}}
          skip: "*.lua,*.ts,codespell.yml,vcpkg/*"
          ignore_words_list: "spPort,build-in,pIce,splitted"
