# Author: Kang Lin<kl222@126.com>

name: Doxygen

on:
  workflow_call:
    outputs:
      name:
        description: "The artifact name"
        value: ${{ jobs.build_doxygen.outputs.name }}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_TYPE:  Release
      SOURCE_DIR:  ${{github.workspace}}/.cache/source
      TOOLS_DIR:   ${{github.workspace}}/.cache/tools
      INSTALL_DIR: ${{github.workspace}}/.cache/install_ubuntu
      artifact_name: build_doxygen
      DOXYGEN_VERSION: 1.9.8
      RabbitIm_VERSION: v0.0.27

    # Map the job outputs to step outputs
    outputs:
      name: ${{ env.artifact_name }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    
    - name: make_directory
      run: |
        cmake -E make_directory ${{env.SOURCE_DIR}}
        cmake -E make_directory ${{env.TOOLS_DIR}}
        cmake -E make_directory ${{env.INSTALL_DIR}}
        cmake -E make_directory ${{github.workspace}}/build

    - name: Cache installed
      uses: actions/cache@v4
      id: cache-installed
      with:
        path: |
          ${{env.TOOLS_DIR}}
        key: install-doxygen
    
    - name: git clone RabbitCommon
      working-directory: ${{env.SOURCE_DIR}}
      run: git clone https://github.com/KangLin/RabbitCommon.git

    - name: install apt packages
      run: |
        sudo ./Script/build_depend.sh --system_update --base --default --install ${{env.INSTALL_DIR}}
      
    - name: Download doxygen
      run: |
        if [ ! -d ${{env.TOOLS_DIR}}/doxygen-${{env.DOXYGEN_VERSION}} ]; then
            cd ${{env.TOOLS_DIR}}
            wget https://www.doxygen.nl/files/doxygen-${{env.DOXYGEN_VERSION}}.linux.bin.tar.gz
            tar xzf doxygen-${{env.DOXYGEN_VERSION}}.linux.bin.tar.gz
        fi
        sudo cp ${{env.TOOLS_DIR}}/doxygen-${{env.DOXYGEN_VERSION}}/bin/doxygen /usr/bin/doxygen

    - name: build doxygen
      working-directory: ${{github.workspace}}
      env:
        RabbitCommon_ROOT: ${{env.SOURCE_DIR}}/RabbitCommon
        BUILD_DOCS: ON
      run: |
        cmake -E make_directory ${{github.workspace}}/build
        cd ${{github.workspace}}/build
        cmake ${{github.workspace}} \
            -DBUILD_APP:BOOL=OF \
            -DBUILD_CLIENT:BOOL=OFF \
            -DBUILD_PLUGINS:BOOL=OFF \
            -DBUILD_SERVICE:BOOL=OFF \
            -DBUILD_ABOUT:BOOL=OFF \
            -DBUILD_ADMINAUTHORISER:BOOL=OFF \
            -DBUILD_UPDATE:BOOL=OFF \
            -DWITH_CMARK=OFF \
            -DWITH_CMARK_GFM=OFF \
            -DCMARK_SHARED=OFF \
            -DCMARK_TESTS=OFF \
            -DCMARK_STATIC=ON \
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
            -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/build/install \
            -DBUILD_DOCS=ON
        cmake --build . --target doc_Chinese doc_English

    - name: Update artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.artifact_name }}
        path: |
          ${{github.workspace}}/build/RabbitIm_${{env.RabbitIm_VERSION}}_document.zip
      
    - name: Deploy to GitHub Pages
      if: startsWith(github.ref, 'refs/tags/')
      uses: crazy-max/ghaction-github-pages@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        target_branch: gh-pages
        build_dir: build/Doxygen
