# Author: Kang Lin <kl222@126.com>

name: macos

on:
  workflow_call:
    outputs:
      name:
        description: "The artifact name"
        value: ${{ jobs.build_macos.outputs.name }}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build_macos:
    strategy:
      matrix:
        include:
          - VCPKG_TARGET_TRIPLET: x64-osx
            os: macos-15-intel
            qt_version: 6.9.3
            qt_arch: clang_64
            WITH_MACOSX_BUNDLE: false

          - VCPKG_TARGET_TRIPLET: arm64-osx
            os: macos-14
            qt_version: 6.9.3
            qt_arch: clang_64
            WITH_MACOSX_BUNDLE: true
        
          - VCPKG_TARGET_TRIPLET: arm64-osx
            os: macos-14
            qt_version: 6.9.3
            qt_arch: clang_64
            WITH_MACOSX_BUNDLE: false
            
    # See: [About GitHub-hosted runners](https://docs.github.com/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners)
    # See: [Choosing the runner for a job](https://docs.github.com/actions/writing-workflows/choosing-where-your-workflow-runs/choosing-the-runner-for-a-job)
    # See: https://github.com/actions/runner-images/
    runs-on: ${{matrix.os}}

    env:
      BUILD_TYPE:  ${{ matrix.BUILD_TYPE }}
      SOURCE_DIR:  ${{github.workspace}}/.cache/source
      TOOLS_DIR:   ${{github.workspace}}/.cache/tools
      INSTALL_DIR: ${{github.workspace}}/.cache/install_macos_qt${{matrix.qt_version}}_${{matrix.BUILD_TYPE}}
      BUILD_DIR:   ${{github.workspace}}/build
      qt_modules:  "qtscxml qtmultimedia qtserialport qt5compat qtwebsockets qtpositioning qtwebchannel qtwebengine"
      VCPKG_TARGET_TRIPLET: ${{matrix.VCPKG_TARGET_TRIPLET}}
      VCPKG_DEFAULT_TRIPLET: ${{matrix.VCPKG_TARGET_TRIPLET}}     
      VCPKGGITCOMMITID: 7213cf8135c329c37c7e2778e40774489a0583a8
      artifact_name: build_macos
      RabbitIM_VERSION: v1.0.9

    # Map the job outputs to step outputs
    outputs:
      name: ${{ env.artifact_name }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
    
      - name: Make directories
        run: |
          cmake -E make_directory ${{env.SOURCE_DIR}}
          cmake -E make_directory ${{env.TOOLS_DIR}}
          cmake -E make_directory ${{env.INSTALL_DIR}}
          cmake -E make_directory ${{env.BUILD_DIR}}

      - name: Cache installed
        uses: actions/cache@v4
        id: cache-installed
        with:
          path: |
            ${{env.INSTALL_DIR}}
          key: install_macos_${{env.VCPKG_TARGET_TRIPLET}}

      - name: run-vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: ${{env.VCPKGGITCOMMITID}}
          vcpkgDirectory: ${{env.SOURCE_DIR}}/vcpkg          

      - name: install nasm
        run: |
          # See: https://formulae.brew.sh/
          brew update
          brew install nasm autoconf automake libtool pkg-config zstd libpcap libvncserver # pcapplusplus qt qtkeychain
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          dir: '${{env.TOOLS_DIR}}/qt' # optional
          version: '${{matrix.qt_version}}' # optional, default is 5.15.2
          arch: '${{matrix.qt_arch}}' # optional
          modules: '${{env.qt_modules}}' # optional. See: https://ddalcino.github.io/aqt-list-server/
          cache: true
          cache-key-prefix: cached-qt_${{matrix.qt_version}}_${{matrix.qt_arch}}

      - name: build qxmpp
        working-directory: ${{env.SOURCE_DIR}}
        run: |
          if [ ! -d ${{env.INSTALL_DIR}}/lib/cmake/qxmpp ]; then
            git clone -b v1.10.3 https://invent.kde.org/libraries/qxmpp.git
            cd qxmpp
            cmake -E make_directory build
            cd build
            cmake .. \
                -DCMAKE_BUILD_TYPE=Release \
                -DBUILD_EXAMPLES=OFF -DBUILD_TESTS=OFF \
                -DCMAKE_INSTALL_PREFIX=${{env.INSTALL_DIR}} \
                -DCMAKE_PREFIX_PATH=${{env.INSTALL_DIR}}/lib/cmake \
                -DCMAKE_TOOLCHAIN_FILE="${{env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake" \
                -DX_VCPKG_APPLOCAL_DEPS_INSTALL=ON \
                -DVCPKG_VERBOSE=ON \
                -DVCPKG_TARGET_TRIPLET=${{matrix.VCPKG_TARGET_TRIPLET}}
            cmake --build . --config Release
            cmake --install . --config Release --strip
          fi
      
      - name: Compile
        working-directory: ${{github.workspace}}/build
        run: |
          cmake ${{github.workspace}} \
              -DCMARK_SHARED=OFF \
              -DCMARK_TESTS=OFF \
              -DCMARK_STATIC=ON \
              -DWITH_CMARK=OFF \
              -DWITH_CMARK_GFM=ON \
              -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/build/install \
              -DCMAKE_PREFIX_PATH=${{env.INSTALL_DIR}}/lib/cmake \
              -DCMAKE_TOOLCHAIN_FILE="${{env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake" \
              -DX_VCPKG_APPLOCAL_DEPS_INSTALL=ON \
              -DVCPKG_VERBOSE=ON \
              -DVCPKG_TARGET_TRIPLET=${{matrix.VCPKG_TARGET_TRIPLET}} \
              -DRABBIT_WITH_MACDEPLOY=OFF \
              -DWITH_MACOSX_BUNDLE=ON
          cmake --build . --config ${{ matrix.BUILD_TYPE }} --target install
          cmake --build . --config ${{ matrix.BUILD_TYPE }} --target package
          7z a RabbitCommon_${{env.RabbitIM_VERSION}}_macos.zip ./install/*

      - name: Update artifact
        if: ${{ matrix.BUILD_TYPE == 'Release' }} 
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifact_name }}
          path: |
            ${{github.workspace}}/build/RabbitCommon-*.tar.gz
            ${{github.workspace}}/build/RabbitCommon_${{env.RabbitIM_VERSION}}_macos.zip
