# Author: Kang Lin <kl222@126.com>

name: build_msvc

on:
  workflow_call:
    outputs:
      name:
        description: "The artifact name"
        value: ${{ jobs.build_msvc.outputs.name }}

jobs:
  build_msvc:

    strategy:
      matrix:
        include:
          - CMAKE_GENERATOR_PLATFORM: x64
            VCPKG_TARGET_TRIPLET: x64-windows
            VCPKG_PLATFORM_TOOLSET: v143
            qt_version: 6.9.3
            qt_arch: win64_msvc2022_64
            qt_modules: qtscxml qtmultimedia qtimageformats qtserialport qt5compat qtwebsockets qtpositioning qtwebchannel qtwebengine
            BUILD_TYPE: Release
            os: windows-2022

          - CMAKE_GENERATOR_PLATFORM: arm64
            VCPKG_TARGET_TRIPLET: arm64-windows
            VCPKG_PLATFORM_TOOLSET: v143
            qt_version: 6.9.3
            qt_arch: win64_msvc2022_arm64
            qt_modules: qt5compat qtimageformats qtmultimedia qtpositioning qtscxml qtserialport qtwebchannel qtwebsockets
            BUILD_TYPE: Release
            os: windows-11-arm

          - CMAKE_GENERATOR_PLATFORM: Win32
            VCPKG_TARGET_TRIPLET: x86-windows
            VCPKG_PLATFORM_TOOLSET: v143
            VCPKG_OVERLAY_PORTS: "vcpkg/ports"
            #VCPKG_MANIFEST_FEATURES: "ffmpeg"
            qt_version: 5.15.2
            qt_arch: win32_msvc2019
            qt_modules: qtwebengine
            BUILD_TYPE: Release
            os: windows-2022

    # See: [About GitHub-hosted runners](https://docs.github.com/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners)
    # See: [Choosing the runner for a job](https://docs.github.com/actions/writing-workflows/choosing-where-your-workflow-runs/choosing-the-runner-for-a-job)
    # See: https://github.com/actions/runner-images/
    runs-on: ${{matrix.os}}

    env:
      SOURCE_DIR:  ${{github.workspace}}\.cache\source
      TOOLS_DIR:   ${{github.workspace}}\.cache\tools
      INSTALL_DIR: ${{github.workspace}}\.cache\install_msvc_qt${{matrix.qt_version}}_${{matrix.triplet}}_${{matrix.BUILD_TYPE}}
      BUILD_DIR:   ${{github.workspace}}\build
      VCPKGGITCOMMITID: 4c5ae6b55f3e3e39d291679f89822f496cf190ee
      VCPKG_TARGET_TRIPLET: ${{matrix.VCPKG_TARGET_TRIPLET}}
      VCPKG_DEFAULT_TRIPLET: ${{matrix.VCPKG_TARGET_TRIPLET}}
      VCPKG_PLATFORM_TOOLSET: ${{matrix.VCPKG_PLATFORM_TOOLSET}}
      VCPKG_OVERLAY_PORTS: "${{github.workspace}}/${{matrix.VCPKG_OVERLAY_PORTS}}"
      VCPKG_MANIFEST_FEATURES: "freerdp;vnc;terminal;filetransfer"
      VCPKG_INSTALLED_DIR: ${{github.workspace}}\.cache\install
      CMAKE_GENERATOR: "Visual Studio 17 2022"
      CMAKE_GENERATOR_PLATFORM: ${{matrix.CMAKE_GENERATOR_PLATFORM}}
      qt_modules: "${{matrix.qt_modules}}"
      RabbitIM_VERSION: v0.0.27
      artifact_name: build_msvc

    # Map the job outputs to step outputs
    outputs:
      name: ${{ env.artifact_name }}
      
    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Make directories
        run: |
          cmake -E make_directory ${{env.BUILD_DIR}}
          cmake -E make_directory ${{env.SOURCE_DIR}}
          cmake -E make_directory ${{env.TOOLS_DIR}}
          cmake -E make_directory ${{env.INSTALL_DIR}}
          
      - name: Cache installed
        uses: actions/cache@v4
        id: cache-installed
        with:
          path: |
            ${{env.INSTALL_DIR}}
          key: install_msvc_qt${{matrix.qt_version}}_${{matrix.qt_arch}}_${{matrix.BUILD_TYPE}}

      - name: run-vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: ${{env.VCPKGGITCOMMITID}}
          vcpkgDirectory: ${{env.SOURCE_DIR}}/vcpkg

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          dir: '${{env.TOOLS_DIR}}/qt' # optional
          version: '${{matrix.qt_version}}' # optional, default is 5.15.2
          arch: '${{matrix.qt_arch}}' # optional
          modules: '${{env.qt_modules}}' # optional.  see: https://ddalcino.github.io/aqt-list-server/
          cache: true
          cache-key-prefix: cached-qt_${{matrix.qt_version}}_${{matrix.qt_arch}}
      
      - name: build qxmpp
        working-directory: ${{env.SOURCE_DIR}}
        run: |
          IF NOT EXIST ${{env.INSTALL_DIR}}/lib/cmake/qxmpp (
            git clone https://invent.kde.org/libraries/qxmpp.git
            cd qxmpp
            git checkout -b v1.10.3 v1.10.3
            cmake -E make_directory build
            cd build
            cmake .. ^
                -A ${{matrix.CMAKE_GENERATOR_PLATFORM}} ^
                -T ${{matrix.VCPKG_PLATFORM_TOOLSET}} ^
                -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} ^
                -DBUILD_EXAMPLES=OFF -DBUILD_TESTS=OFF ^
                -DBUILD_DOCUMENTATION=OFF ^
                -DCMAKE_INSTALL_PREFIX=${{env.INSTALL_DIR}} ^
                -DCMAKE_PREFIX_PATH=${{env.INSTALL_DIR}}/lib/cmake ^
                -DCMAKE_TOOLCHAIN_FILE=${{env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake ^
                -DVCPKG_INSTALLED_DIR=${{env.INSTALL_DIR}}/qxmpp/vcpkg_installed ^
                -DVCPKG_VERBOSE=ON ^
                -DVCPKG_TARGET_TRIPLET=${{matrix.VCPKG_TARGET_TRIPLET}} ^
                -DX_VCPKG_APPLOCAL_DEPS_INSTALL=OFF ^
                -DVCPKG_APPLOCAL_DEPS=OFF ^
                -DVCPKG_TRACE_FIND_PACKAGE=ON
            cmake --build . --config ${{matrix.BUILD_TYPE}}
            cmake --install . --config ${{matrix.BUILD_TYPE}} --strip
          )

      - name: git clone RabbitCommon
        working-directory: ${{env.SOURCE_DIR}}
        run: git clone https://github.com/KangLin/RabbitCommon.git

      - name: Build RabbitIM
        working-directory: ${{env.BUILD_DIR}}
        env:
          RabbitCommon_DIR: ${{env.SOURCE_DIR}}/RabbitCommon
        run: |
          cmake ${{github.workspace}} ^
              -A ${{matrix.CMAKE_GENERATOR_PLATFORM}} ^
              -T ${{matrix.VCPKG_PLATFORM_TOOLSET}} ^
              -DCMARK_SHARED=OFF ^
              -DCMARK_TESTS=OFF ^
              -DCMARK_STATIC=ON ^
              -DWITH_CMARK=OFF ^
              -DWITH_CMARK_GFM=ON ^
              -DRABBIT_ENABLE_INSTALL_DEPENDENT=ON ^
              -DRABBIT_ENABLE_INSTALL_QT=ON ^
              -DRABBIT_ENABLE_INSTALL_TO_BUILD_PATH=ON ^
              -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} ^
              -DCMAKE_INSTALL_PREFIX=${{env.BUILD_DIR}}/install ^
              -DCMAKE_PREFIX_PATH=${{env.INSTALL_DIR}} ^
              -DCMAKE_TOOLCHAIN_FILE=${{env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake ^
              -DVCPKG_VERBOSE=ON ^
              -DVCPKG_TARGET_TRIPLET=${{matrix.VCPKG_TARGET_TRIPLET}} ^
              -DX_VCPKG_APPLOCAL_DEPS_INSTALL=ON ^
              -DVCPKG_APPLOCAL_DEPS=ON ^
              -DVCPKG_TRACE_FIND_PACKAGE=ON
          cmake --build . --config ${{matrix.BUILD_TYPE}}
          IF "${{matrix.BUILD_TYPE}}" == "Release" (
            echo "cmake install config: ${{matrix.BUILD_TYPE}} component: Runtime"
            cmake --install . --config ${{matrix.BUILD_TYPE}} --component Runtime --strip
            echo "cmake install config: ${{matrix.BUILD_TYPE}} component: Plugin"
            cmake --install . --config ${{matrix.BUILD_TYPE}} --component Plugin --strip
            echo "cmake install config: ${{matrix.BUILD_TYPE}} component: DependLibraries"
            cmake --install . --config ${{matrix.BUILD_TYPE}} --component DependLibraries --strip
            echo "cmake install config: ${{matrix.BUILD_TYPE}} component: Application"
            cmake --install . --config ${{matrix.BUILD_TYPE}} --component Application --strip
          ) else (
            echo "cmake install config: ${{matrix.BUILD_TYPE}} component: Runtime Application Plugin"
            cmake --install . --config ${{matrix.BUILD_TYPE}} --component Runtime
            cmake --install . --config ${{matrix.BUILD_TYPE}} --component Plugin
            cmake --install . --config ${{matrix.BUILD_TYPE}} --component DependLibraries
            cmake --install . --config ${{matrix.BUILD_TYPE}} --component Application
          )

      - name: Package
        if: ${{ matrix.BUILD_TYPE == 'Release' }}
        working-directory: ${{github.workspace}}\build
        run: |
          move /Y install\plugins\*crypto*.dll install\bin
          move /Y install\plugins\*ssl*.dll install\bin
          copy /Y ${{env.INSTALL_DIR}}\bin\*.dll install\bin
          copy /Y ${{env.INSTALL_DIR}}\lib\*.dll install\bin
          copy /Y ${{env.RUNVCPKG_VCPKG_ROOT}}\installed\${{env.RUNVCPKG_VCPKG_TRIPLET_OUT}}\bin\*.dll install\bin
          7z a RabbitIM_windows_${{env.RabbitIM_VERSION}}.zip .\install\*
          md5sum RabbitIM_windows_${{env.RabbitIM_VERSION}}.zip > RabbitIM_windows_${{env.RabbitIM_VERSION}}.zip.md5sum
          makensis Install.nsi
          md5sum RabbitIM_Setup_${{env.RabbitIM_VERSION}}.exe > RabbitIM_Setup_${{env.RabbitIM_VERSION}}.exe.md5sum
          ${{github.workspace}}\build\install\bin\RabbitIMApp.exe ^
                -f "update_windows.xml" ^
                -u https://github.com/KangLin/RabbitIM/releases/download/${{env.RabbitIM_VERSION}}/RabbitIM_Setup_${{env.RabbitIM_VERSION}}.exe;https://sourceforge.net/projects/RabbitIM/files/${{env.RabbitIM_VERSION}}/RabbitIM_Setup_${{env.RabbitIM_VERSION}}.exe ^
                --pf RabbitIM_Setup_${{env.RabbitIM_VERSION}}.exe ^
                -m "${{env.RabbitIM_VERSION}}"

      - name: Update artifact
        if: ${{ matrix.BUILD_TYPE == 'Release' && '5.12.12' == matrix.qt_version }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.artifact_name }}
          path: |
            ${{github.workspace}}\build\RabbitIM_Setup_${{env.RabbitIM_VERSION}}.exe
            ${{github.workspace}}\build\update_windows.xml
        #if: ${{ matrix.BUILD_TYPE == 'Release' }}

#    - name: Upload To Github Release
#      if: ${{ matrix.BUILD_TYPE == 'Release' && '5.12.12' == matrix.qt_version && startsWith(github.ref, 'refs/tags/') }}
#      uses: softprops/action-gh-release@v0.1.14
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      with:
#        prerelease: true
##        body: |
##          [:cn: 修改日志](ChangeLog_zh_CN.md) [:cn: 说明](README_zh_CN.md)
##          [:us: Change log](ChangeLog.md) [:us: README](README.md)
#        files: |
#          ${{github.workspace}}\build\RabbitIM_windows_${{env.RabbitIM_VERSION}}.zip
#          ${{github.workspace}}\build\RabbitIM_windows_${{env.RabbitIM_VERSION}}.zip.md5sum
#          ${{github.workspace}}\build\RabbitIM_Setup_${{env.RabbitIM_VERSION}}.exe
#          ${{github.workspace}}\build\RabbitIM_Setup_${{env.RabbitIM_VERSION}}.exe.md5sum
#          ${{github.workspace}}\build\update_windows.xml
