name: ubuntu

on:
  workflow_call:
    outputs:
      name:
        description: "The artifact name"
        value: ${{ jobs.build_ubuntu.outputs.name }}

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  build_ubuntu:
    strategy:
      matrix:
        BUILD_TYPE: [Release, Debug]

    runs-on: ubuntu-latest

    env:
      BUILD_TYPE:  ${{matrix.BUILD_TYPE}}
      SOURCE_DIR:  ${{github.workspace}}/.cache/source
      TOOSL_DIR:   ${{github.workspace}}/.cache/tools
      INSTALL_DIR: ${{github.workspace}}/.cache/install_ubuntu_${{matrix.BUILD_TYPE}}
      RabbitIM_VERSION: 0.0.27
      artifact_name: build_ubuntu

    # Map the job outputs to step outputs
    outputs:
      name: ${{ env.artifact_name }}

    steps:
      - name: core dump infomations
        if: false
        run: |
          echo "# ulimit -a"
          ulimit -a
          echo "# cat /proc/sys/kernel/core_pattern"
          cat /proc/sys/kernel/core_pattern
          echo "# ulimit -c unlimited"
          ulimit -c unlimited
          echo "# sudo sysctl -w kernel.core_pattern=core"
          sudo sysctl -w kernel.core_pattern=${{github.workspace}}/core
          echo "# ulimit -a"
          ulimit -a
          echo "# cat /proc/sys/kernel/core_pattern"
          cat /proc/sys/kernel/core_pattern

#        See: https://www.cnblogs.com/cong-wang/p/15026524.html
#        Naming of core dump files
#               By default, a core dump file is named core, but the /proc/sys/kernel/core_pattern file (since  Linux  2.6  and
#               2.4.21)  can  be  set  to  define a template that is used to name core dump files.  The template can contain %
#               specifiers which are substituted by the following values when a core file is created:
#
#                   %%  a single % character
#                   %c  core file size soft resource limit of crashing process (since Linux 2.6.24)
#                   %d  dump mode—same as value returned by prctl(2) PR_GET_DUMPABLE (since Linux 3.7)
#                   %e  executable filename (without path prefix)
#                   %E  pathname of executable, with slashes ('/') replaced by exclamation marks ('!') (since Linux 3.0).
#                   %g  (numeric) real GID of dumped process
#                   %h  hostname (same as nodename returned by uname(2))
#                   %i  TID of thread that triggered core dump, as seen in the PID  namespace  in  which  the  thread  resides
#                       (since Linux 3.18)
#                   %I  TID of thread that triggered core dump, as seen in the initial PID namespace (since Linux 3.18)
#                   %p  PID of dumped process, as seen in the PID namespace in which the process resides
#                   %P  PID of dumped process, as seen in the initial PID namespace (since Linux 3.12)
#                   %s  number of signal causing dump
#                   %t  time of dump, expressed as seconds since the Epoch, 1970-01-01 00:00:00 +0000 (UTC)
#                   %u  (numeric) real UID of dumped process

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Make directories
        run: |
          cmake -E make_directory ${{env.SOURCE_DIR}}
          cmake -E make_directory ${{env.TOOSL_DIR}}
          cmake -E make_directory ${{env.INSTALL_DIR}}
          cmake -E make_directory ${{github.workspace}}/build

      - name: git clone RabbitCommon
        working-directory: ${{env.SOURCE_DIR}}
        run: |
            git clone -b v2 https://github.com/KangLin/RabbitCommon.git

      - name: Install apt packages
        run: |
          sudo apt-get update -y
          sudo apt-get upgrade -y
          sudo apt install -y -q cmake build-essential xvfb xpra \
              libglu1-mesa-dev libpulse-mainloop-glib0 \
              cmake debhelper fakeroot \
              qt6-tools-dev qt6-tools-dev-tools \
              qt6-base-dev qt6-base-dev-tools qt6-qpa-plugins \
              libqt6svg6-dev qt6-l10n-tools qt6-translations-l10n \
              qt6-scxml-dev qt6-multimedia-dev libqt6serialport6-dev \
              qt6-webengine-dev qt6-webengine-dev-tools \
              libxkbcommon-dev libxkbcommon-x11-dev xorg-dev libx11-xcb-dev \
              libx11-dev libxfixes-dev

      - name: Cache installed
        uses: actions/cache@v3
        id: cache-installed
        with:
          path: |
            ${{env.INSTALL_DIR}}
          key: cache-installed-ubuntu

      - name: build_debpackage.sh
        working-directory: ${{github.workspace}}
        env:
          RabbitCommon_DIR: ${{env.SOURCE_DIR}}/RabbitCommon
        run: |
          if [ ${{matrix.BUILD_TYPE}} == 'Release' ]; then
              export BUILD_VIEWER_TERMINAL=OFF
          else
              export tigervnc_DIR=${{env.INSTALL_DIR}}/lib/cmake/tigervnc
          fi
          export Qt6_DIR=/usr/lib/`uname-a`-linux-gnu/cmake/Qt6
          ./build_debpackage.sh
          cp ../RabbitIM_${{env.RabbitIM_VERSION}}_amd64.deb RabbitIM_${{env.RabbitIM_VERSION}}_amd64.deb
          md5sum RabbitIM_${{env.RabbitIM_VERSION}}_amd64.deb > RabbitIM_${{env.RabbitIM_VERSION}}_amd64.deb.md5sum

      - name: update xml file
        if: ${{ matrix.BUILD_TYPE == 'Release'}}
        working-directory: ${{github.workspace}}
        #continue-on-error: true
        run: |
          #sudo apt update -y -qq
          #sudo apt-get install -y -qq xvfb xpra
          sudo Xvfb :99 -ac &
          export DISPLAY=:99.0
          echo "Install rabbit remote control ......"
          sudo apt install ./RabbitIM_${{env.RabbitIM_VERSION}}_amd64.deb
          #echo "ls -l /opt/RabbitIM/bin/"
          #ls -l /opt/RabbitIM/bin/
          echo "Update update_linux.xml ......"
          export QT_XCB_GL_INTEGRATION=none
          MD5SUM=`cat RabbitIM_${{env.RabbitIM_VERSION}}_amd64.deb.md5sum|awk '{print $1}'`
          echo "MD5SUM RabbitIM_${{env.RabbitIM_VERSION}}_amd64.deb: ${MD5SUM}"
          #ulimit -c unlimited
          #echo "# sudo sysctl -w kernel.core_pattern=core"
          #sudo sysctl -w kernel.core_pattern=${{github.workspace}}/core
          /opt/RabbitIM/bin/RabbitIM.sh \
            -f "`pwd`/update_linux.xml" \
            -u "https://github.com/KangLin/RabbitIM/releases/download/${{env.RabbitIM_VERSION}}/RabbitIM_${{env.RabbitIM_VERSION}}_amd64.deb;https://sourceforge.net/projects/RabbitIM/files/${{env.RabbitIM_VERSION}}/RabbitIM_${{env.RabbitIM_VERSION}}_amd64.deb" \
            --md5 "${MD5SUM}" \
            --pf RabbitIM_${{env.RabbitIM_VERSION}}_amd64.deb \
            -m "v${{env.RabbitIM_VERSION}}"

      - name: dump core
        if: false
        working-directory: ${{github.workspace}}
        run: |
          gdb /opt/RabbitIM/bin/RabbitIMApp core

      - name: Update artifact
        if: ${{ matrix.BUILD_TYPE == 'Release' }}
        uses: actions/upload-artifact@v3
        with:
            name: ${{ env.artifact_name }}
            path: |
              ${{github.workspace}}/RabbitIM_*.deb
              ${{github.workspace}}/update_linux.xml
